### ISSUE TITLE
Remove edit distance library

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#56]
The edit distance library uses eval. This is a bad idea.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/app/api/sms/__init__.py", line 1, in <module>
    from main import app  # noqa
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/app/api/sms/main.py", line 6, in <module>
    from app.api.sms.plant_action import PlantCommand, PlantAction
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/app/api/sms/plant_action.py", line 2, in <module>
    from app.api.sms.base_action import OneArgCommand
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/app/api/sms/base_action.py", line 1, in <module>
    from app.command.base import Command
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/app/command/base.py", line 1, in <module>
    from app.util.matcher import match
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/app/util/matcher.py", line 1, in <module>
    import editdistance as ed
  File "/base/data/home/apps/s~communicate-indonesia-staging/1.386780269136283218/lib/editdistance/__init__.py", line 1, in <module>
    from .bycython import eval
ImportError: dynamic module does not define init function (initbycython)

**Comment by Ragil** [comment]
https://github.com/Ragil/Communicate-Indonesia/pull/57
